//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DS1Entities : DbContext
    {
        public DS1Entities()
            : base("name=DS1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Role> Role { get; set; }
    
        public virtual ObjectResult<sp_get_users_Result> sp_get_users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_users_Result>("sp_get_users");
        }
    }
}
